export const causalOrganizationsAbi = [
  // --- Write functions ---
  {
    type: "function",
    name: "createOrganization",
    inputs: [
      { name: "name", type: "string" },
      { name: "symbol", type: "string" },
      { name: "description", type: "string" },
      { name: "imageUrl", type: "string" },
      { name: "totalTokenSupply", type: "uint256" },
      { name: "tokensForSale", type: "uint256" },
      { name: "fundingGoal", type: "uint256" },
      { name: "saleDuration", type: "uint256" },
      { name: "alpha", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "commit",
    inputs: [
      { name: "orgId", type: "uint256" },
      { name: "usdcAmount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeRaise",
    inputs: [
      { name: "orgId", type: "uint256" },
      { name: "finalCap", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "forceFinalize",
    inputs: [{ name: "orgId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claim",
    inputs: [{ name: "orgId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // --- Read functions ---
  {
    type: "function",
    name: "orgCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orgSales",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "fundingGoal", type: "uint256" },
      { name: "usdcRaised", type: "uint256" },
      { name: "tokensForSale", type: "uint256" },
      { name: "totalTokenSupply", type: "uint256" },
      { name: "saleStart", type: "uint256" },
      { name: "saleEnd", type: "uint256" },
      { name: "alpha", type: "uint256" },
      { name: "totalAccumulator", type: "uint256" },
      { name: "discretionaryCap", type: "uint256" },
      { name: "capDeadline", type: "uint256" },
      { name: "capSet", type: "bool" },
      { name: "active", type: "bool" },
      { name: "finalized", type: "bool" },
      { name: "successful", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orgTokens",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orgTreasuries",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orgFactories",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "contributions",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "accumulators",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasClaimed",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orgContributorCount",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrgInfo",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "name", type: "string" },
      { name: "symbol", type: "string" },
      { name: "description", type: "string" },
      { name: "imageUrl", type: "string" },
      { name: "founder", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFinalShare",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserAllocation",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [
      { name: "estimatedTokens", type: "uint256" },
      { name: "estimatedRefund", type: "uint256" },
      { name: "finalShareBps", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCurrentMultiplier",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "numerator", type: "uint256" },
      { name: "denominator", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenPrice",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getContributor",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "uint256" },
    ],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFounderOrgCount",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFounderOrgId",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  // --- Events ---
  {
    type: "event",
    name: "OrganizationCreated",
    inputs: [
      { name: "orgId", type: "uint256", indexed: true },
      { name: "founder", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "symbol", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Committed",
    inputs: [
      { name: "orgId", type: "uint256", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "accumulator", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DiscretionaryCapSet",
    inputs: [
      { name: "orgId", type: "uint256", indexed: true },
      { name: "cap", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SaleFinalized",
    inputs: [
      { name: "orgId", type: "uint256", indexed: true },
      { name: "successful", type: "bool", indexed: false },
      { name: "finalRaise", type: "uint256", indexed: false },
      { name: "token", type: "address", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      { name: "orgId", type: "uint256", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "tokens", type: "uint256", indexed: false },
      { name: "refund", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TreasuryDeployed",
    inputs: [
      { name: "orgId", type: "uint256", indexed: true },
      { name: "treasury", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FactoryDeployed",
    inputs: [
      { name: "orgId", type: "uint256", indexed: true },
      { name: "factory", type: "address", indexed: true },
    ],
  },
] as const;
