export const futarchyFactoryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "owner_", type: "address" },
      { name: "treasury_", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createProposal",
    inputs: [
      { name: "title", type: "string" },
      { name: "tokenX", type: "address" },
      { name: "usdc", type: "address" },
      { name: "resolutionTimestamp", type: "uint256" },
      { name: "transferToken", type: "address" },
      { name: "recipient", type: "address" },
      { name: "transferAmount", type: "uint256" },
      { name: "usdcRequested", type: "uint256" },
      { name: "tokensToMint", type: "uint256" },
      { name: "twapWindow_", type: "uint32" },
    ],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createProposalWithAmm",
    inputs: [
      { name: "title", type: "string" },
      { name: "tokenX", type: "address" },
      { name: "usdc", type: "address" },
      { name: "resolutionTimestamp", type: "uint256" },
      { name: "transferToken", type: "address" },
      { name: "recipient", type: "address" },
      { name: "transferAmount", type: "uint256" },
      { name: "usdcRequested", type: "uint256" },
      { name: "tokensToMint", type: "uint256" },
      { name: "twapWindow_", type: "uint32" },
      { name: "uniswapV3Factory_", type: "address" },
      { name: "positionManager_", type: "address" },
      { name: "fee", type: "uint24" },
      { name: "initialPriceYesXUsdcSqrtX96", type: "uint160" },
      { name: "initialPriceNoXUsdcSqrtX96", type: "uint160" },
      { name: "tokenXAmount", type: "uint256" },
      { name: "usdcAmount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "treasury",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposalCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposals",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "previousOwner", type: "address", indexed: true },
      { name: "newOwner", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "ProposalCreatedWithAmm",
    inputs: [
      { name: "proposalId", type: "uint256", indexed: true },
      { name: "proposal", type: "address", indexed: true },
      { name: "ammYesPair", type: "address", indexed: false },
      { name: "ammNoPair", type: "address", indexed: false },
    ],
  },
] as const;
